### ISSUE TITLE
Неполный шаблон

### ISSUE THREAD

**Issue by proffust** [pavlovdo/pystormon#1]
Добрый день
В шаблоне в двух обнаружениях нет никаких прототипов
https://gyazo.com/67f0aab266925db63cb0dc3b44138e95

**Comment by pavlovdo** [comment]
Добрый день
Да, не успел еще добавить по этим сущностям

**Comment by dziugass** [comment]
Thanks for the scripts! Maybe you have some more triggers/items made?

**Comment by shuitianyise** [comment]
Hello ， every body！
the template is to import , is that (Incorrect file upload.)  ,
that is wrong!
Do you have the things to happend????

**Comment by shuitianyise** [comment]
the  python need to python3  and  the  scripts ( storage_discovery.py ) can't run........

**Comment by nickdsl** [comment]
> Hello ， every body！
> the template is to import , is that (Incorrect file upload.) ,
> that is wrong!
> Do you have the things to happend????

1) Open template xml in text editor.
2) Find at the beginning of file lines: 
          `<applications>
                <application>
                    <name>Perfomance</name>
                </application>
            </applications>`  
 
3) Replace it to:
`            <applications>
                <application>
                    <name>Perfomance</name>
                </application>
				<application>
                    <name>Status</name>
                </application>
            </applications>`

Save file and try to import again.
