### ISSUE TITLE
Cannot import template "Storage Pystormon", linked template "ICMP ping" does not exist.

### ISSUE THREAD

**Issue by Wolvverine** [pavlovdo/pystormon#11]
Template Module ICMP Ping not ICMP Ping

```
        "templates": [
            {
                "template": "Storage Pystormon",
                "name": "Storage Pystormon",
                "templates": [
                    {
                        "name": "Template Module ICMP Ping"
                    }
                ],
```

**Comment by pavlovdo** [comment]
Hi Wolvverine!

For Zabbix versions 5.x please use new version of template: Storage Pystormon.json or Storage Pystormon.xml - the template ICMP Ping is used there.
For Zabbix version 4.4 name of icmp template is Template Module ICMP Ping.

**Comment by Wolvverine** [comment]
in testing
in Pystormon.xml is  Template Module ICMP Ping.
, but in master you have ICMP Ping in
Pystormon.xml
Pystormon.json

**Comment by pavlovdo** [comment]
Hi !

Yes, in master Storage Pystormon.json and Storage Pystormon.xml is depend on template ICMP Ping.
Please ask your question.

With best regards,
Denis Pavlov

**Comment by Wolvverine** [comment]
@pavlovdo look in Pull request.

**Comment by pavlovdo** [comment]
Hi wolvverine !

I can't pull your request for change name of template ICMP Ping because Storage Pystormon.json and Storage Pystormon.xml is depend on OFFICIAL template ICMP Ping like i said before:
https://github.com/zabbix/zabbix/blob/release/5.2/templates/module/00icmp_ping/00template_module_icmp_ping.yaml
