### ISSUE TITLE
Feature: Add some graphs in template for hosts

### ISSUE THREAD

**Issue by Wolvverine** [pavlovdo/pystormon#18]
Feature: Add some graphs in template for host

example:

Cumulate graphs in one graphs for:
Total IOPS of VDisks
Transfer rate of VDisks
Write Cache Hit IOPS of VDisks
.....

**Comment by pavlovdo** [comment]
Hi !

I've added two separate prototype graphs for Virtual disks: one - for all IOPS, and one - for all rates.
I see no reason to mix rates and IOPS on the same graph because they have different units of measurement.

With best wishes,
Denis
