### ISSUE TITLE
./storage_objects_discovery.py error

### ISSUE THREAD

**Issue by wuqinghuahua** [pavlovdo/pystormon#20]
Hello, how can I prompt such errors when I execute this script?
![image](https://user-images.githubusercontent.com/119034166/204226823-e2aa80a5-8416-4c54-8027-34d5d8b32ae7.png)

**Comment by pavlovdo** [comment]
Hi, to meet the requirements of pystormon, you have to install python module py-zabbix before pystormon deploying.
Read readme please.

**Comment by wuqinghuahua** [comment]
Hi, Thanks for the successful monitoring
