### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Kynepok** [pavlovdo/pystormon#21]
Hi! Thx for your script, but i'm getting this issue, while trying to run any of script from "pystormon" dir. 
![image](https://user-images.githubusercontent.com/88827908/227900398-c41d34a5-6f13-42c7-ac2f-7c2e0526a6f6.png)

Any suggestions? Thx for response!

**Comment by pavlovdo** [comment]
Hi !

You probably have an incompatibility of SSL libraries on the server and storage. Try to check it - on your monitoring server run next commands:
1. `openssl version`
2. `openssl s_client -connect address_of_your_storage -tls1_2`

**Comment by Kynepok** [comment]
> Hi !
> 
> You probably have an incompatibility of SSL libraries on the server and storage. Try to check it - on your monitoring server run next commands:
> 
> 1. `openssl version`
> 2. `openssl s_client -connect address_of_your_storage -tls1_2`

Thanks for quick answer! The problem gone by itself for about a 30 mins, after i discover it. dont know why :\
Can i ask another question, or should open a new issue?

**Comment by Kynepok** [comment]
> Hi !
> 
> You probably have an incompatibility of SSL libraries on the server and storage. Try to check it - on your monitoring server run next commands:
> 
> 1. `openssl version`
> 2. `openssl s_client -connect address_of_your_storage -tls1_2`

Thanks for quick answer! The problem gone by itself for about a 30 mins, after i discover it. dont know why ..
Can i ask another question, or should open a new issue?

**Comment by pavlovdo** [comment]
For another question open new issue please.

**Comment by Kynepok** [comment]
> For another question open new issue please.

sure, thanks.
