### ISSUE TITLE
FileNotFoundError devices.conf

### ISSUE THREAD

**Issue by sacy80** [pavlovdo/pystormon#6]
hi i have encounter this issue on crontab.
![image](https://user-images.githubusercontent.com/30169265/91655361-95812a00-eae2-11ea-8b7a-f15125585a37.png)

but i run it on console it can run ./storage_discovery.py

**Comment by pavlovdo** [comment]
Hi

I fixed devices.conf path to absolute in last commit.
Pull it and try again.

WBR, Denis

**Comment by sacy80** [comment]
hi 

thanks alot. it run now. 

would like to check on zabbix host. have added the storage device. but which interface type to use? agent/snmp/ipmi/jxm? and the ip to point to?

**Comment by pavlovdo** [comment]
You should use Agent interface in zabbix host, and set IP - management IP-address of your storwize storage, where you connect for GUI management. By the way, this IP used in template only for ICMP monitoring of management interface. Data from sensors are mining and sending via zabbix trappers when run python scripts from cron, and IP of storages must be set in the devices.conf configuration file.
