### ISSUE TITLE
Using Zabbix Proxy 

### ISSUE THREAD

**Issue by TroyCollin** [pavlovdo/pystormon#9]
Good day, This script is great..
When I run the storage_cim_print.py I can see the data collected but nothing ends up in zabbix. I'm using a zabbix proxy server is there something I need to add to make this work?
thanks
Troy.

**Comment by pavlovdo** [comment]
Hi, script storage_cim_print.py is needed for check access to your storage or view ALL properties and property's values of those storage objects that are specified in the file storage_cim_map.json.
Also you can add new objects and classes in file storage_cim_map.json, run script storage_cim_print.py and view its properties and property's values.
For example, existing classes for IBM Storwize you can see in https://www.ibm.com/support/knowledgecenter/STHGUJ_8.3.1/com.ibm.storwize.v5000.831.doc/svc_conceptsmaptocimconcepts_3skacv.html and https://www.ibm.com/support/knowledgecenter/STHGUJ_8.3.1/com.ibm.storwize.v5000.831.doc/svc_poolmanipulation_1rno9v.html

For sending data to zabbix use other scripts please:
storage_objects_discovery.py
storage_objects_status.py
storage_perfomance.py

**Comment by TroyCollin** [comment]
Thanks for getting back to me, however yes I used storage_cim_print.py only to test that I'm able to collect data. I have been trying to run storage_objects_discovery.py and storage_objects_status.py but no data is sent. Is there something different I need to setup to make this work via zabbix proxy server? I see no errors  when running storage_objects_discovery.py. 
thank you
Troy.

**Comment by pavlovdo** [comment]
pystormon scripts send data to zabbix trappers running on zabbix server (or zabbix proxy) host.
Did you send data to zabbix proxy ? Zabbix trappers is running on your zabbix proxy ?
Did you import template pystormon, create host for storage and link host with template on your zabbix server ?
Your storage host name in Zabbix is the same as the storage name in pystormon devices.conf ?
Could you send test data via zabbix_sender (Zabbix sender utility) from host where run pystormon scripts to zabbix server or zabbix proxy (zabbix_server from pystormon.conf) and view this data ?

**Comment by TroyCollin** [comment]
Good afternoon, I'm so sorry.. that's what I was missing the trapper.. it's all working now. Thank you very much this is brilliant work by the way. thanks again.

**Comment by pavlovdo** [comment]
It's ok. I'm glad to hear that you receive your data :)
You're welcome.

**Comment by pavlovdo** [comment]
Issue resolved

**Comment by sanemogi** [comment]
Hi, could you please guide me on how to activate trappers on the zabbix proxy ?

**Comment by pavlovdo** [comment]
Hi!

For enable zabbix trappers on zabbix proxy or zabbix servers, you need to set parameter StartTrappers = number_of_trappers in zabbix proxy configuration file,
for example:
StartTrappers = 5
After this restart zabbix proxy service and check running zabbix trappers via command:
```
# ps aux | grep trapper
zabbix    776389  0.2  0.4 2049416 111772 ?      S    дек07  63:41 /usr/sbin/zabbix_server: trapper #1 [processed data in 0.000166 sec, waiting for connection]
zabbix    776390  0.2  0.4 2049512 112016 ?      S    дек07  63:43 /usr/sbin/zabbix_server: trapper #2 [processed data in 0.000342 sec, waiting for connection]
zabbix    776391  0.2  0.4 2049452 112092 ?      S    дек07  63:12 /usr/sbin/zabbix_server: trapper #3 [processed data in 0.000301 sec, waiting for connection]
zabbix    776392  0.2  0.4 2049600 112064 ?      S    дек07  63:57 /usr/sbin/zabbix_server: trapper #4 [processed data in 0.000187 sec, waiting for connection]
zabbix    776393  0.2  0.4 2049412 111836 ?      S    дек07  63:31 /usr/sbin/zabbix_server: trapper #5 [processed data in 0.000176 sec, waiting for connection]
```
More details in https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_proxy.

**Comment by sanemogi** [comment]
Hi Denis,

Thank you for the prompt reply, really appreciate it.

We have enabled zabbix trappers on Zabbix Proxy and the trappers are running.

However, still we see no data in Zabbix. The config files we use are the following:

devices.conf
----------------------------
WBL_IBM_V5100_Storage:192.168.0.102

[NetworkDevice]
device_file = /etc/zabbix/externalscripts/pystormon/conf.d/devices.conf
login = root
name_space = root/ibm
password = XXXXXXXXXX
zabbix_server = 192.168.0.212
slack_hook = https://hooks.slack.com/services/...

[StorageDevice]
storage_cim_map_file = /etc/zabbix/externalscripts/pystormon/conf.d/storage_cim_map.json
printing = False

Do you see any problem with the configuration above ?

Network access from Zabbix Proxy to IBM Storage on port 5989 is permitted

Thank you,

**Comment by TroyCollin** [comment]
Sorry, I'm not able to get the configs right now.. but this worked fantastic for me. Once I got the Traps setup on the proxy server and configured the zabbix server for the items it was great.

thanks
Troy



Troy Collin | Senior Systems Engineer
tcollin@nextdimensioninc.com
Tel: +1-519-883-1172 x502
www.nextdimensioninc.com


Follow us on:
[http://www.nextdimensioninc.com/static/facebook-icon.jpg]<https://www.facebook.com/ndinc.ca>  [http://www.nextdimensioninc.com/static/twitter-icon.jpg] <https://twitter.com/NextDimensionCA>   [http://www.nextdimensioninc.com/static/linkedin-icon.jpg] <http://www.linkedin.com/company/147176?trk=tyah>


[http://www.nextdimensioninc.com/static/banner.jpg]





-----Original Message-----

**Comment by pavlovdo** [comment]
Hi, sanemogi!

Please check naming of device.
To see data from storage in zabbix the name of device has to be the same in devices.conf and in zabbix: WBL_IBM_V5100_Storage

And your devices.conf should see like:
storwize:WBL_IBM_V5100_Storage:192.168.0.102

**Comment by sanemogi** [comment]
Hi, 

The devices.conf is:    storwize:WBL_IBM_V5100_Storage:192.168.0.202
But still we are not getting any data

Any suggestions ?

**Comment by pavlovdo** [comment]
Hi,

What's name of your storage host in Zabbix ?
Did you check printing data from you storage via /etc/zabbix/externalscripts/pystormon/storage_cim_print.py ?

This issue was closed early, so if you still have a problem, please open new issue.
